name: CI

on: [push, pull_request]

env:
  PACKAGE_NAME: 'oxid-esales/easycredit-module'
  MODULE_PATH: 'vendor/oxid-professional-services/easycredit-module'
  MODULE_TESTS_PATH: 'vendor/oxid-professional-services/easycredit-module/tests'
  MODULE_BRANCH: 'dev-main'
  OXID_PATH: '/tmp/oxid7'

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        oxid-versions: ['dev-b-7.0-ce', 'dev-b-7.1-ce', 'dev-b-7.2-ce', 'dev-b-7.3-ce', 'dev-b-7.4-ce', 'dev-b-7.5-ce']
        php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        exclude:
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.2'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.3'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.3'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.2'
    name: Oxid ${{ matrix.oxid-versions }} on PHP ${{ matrix.php-versions }}
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xdebug, gd, bcmath, ctype, curl, dom, hash, iconv, intl, openssl, simplexml, soap, xsl, zip
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Setup Oxid 7
        run: |
          mkdir $OXID_PATH
          cd $OXID_PATH
          composer create-project -n --no-progress --no-install oxid-esales/oxideshop-project . ${{ matrix.oxid-versions }}
          composer config audit.block-insecure false
          composer install --no-interaction
          cp $OXID_PATH/source/config.inc.php.dist $OXID_PATH/source/config.inc.php
          sed -i 's|<dbHost>|127.0.0.1|; s|<dbName>|oxid7|; s|<dbUser>|root|; s|<dbPwd>|root|; s|<dbPort>|3306|; s|<sShopURL>|http://localhost|; s|<sShopDir>|/tmp/oxid7/source|; s|<sCompileDir>|$OXID_PATH/source/tmp|; s|\$this->iDebug = 0|\$this->iDebug = 1|' $OXID_PATH/source/config.inc.php
          sed -i "s|\$this->edition = ''|\$this->edition = 'CE'|" $OXID_PATH/source/config.inc.php
          chmod -R 777 $OXID_PATH/source/log
          
      - name: Checkout current module
        uses: actions/checkout@v5
        with:
          path: $MODULE_PATH
          
      - name: Install Module in Oxid
        run: |
          cd $OXID_PATH
          ls -la $OXID_PATH/$MODULE_PATH
          vendor/bin/oe-console oe:module:install $MODULE_PATH          

      - name: Install module
        run: |
          cd $OXID_PATH
          composer config repositories.PACKAGE_NAME\
            --json '{"type":"path", "url":"$OXID_PATH/$MODULE_PATH", "options": {"symlink": true}}'
          composer config audit.block-insecure false
          composer require $PACKAGE_NAME:* --no-interaction --no-update       

      - name: Install Dev Dependencies
        run: |
          sed -i 's/"minimum-stability": "stable",/"minimum-stability": "dev",/' $OXID_PATH/composer.json
          cd $OXID_PATH
          composer require --dev -n --no-progress oxid-esales/testing-library:dev-b-8.0.x
          composer install --no-interaction

            

          
          
