name: CI

on: [push, pull_request]

env:
  PACKAGE_NAME: 'oxid-professional-services/easycredit-module'
  MODULE_PATH: 'vendor/oxid-professional-services/easycredit-module'
  MODULE_TESTS_PATH: 'vendor/oxid-professional-services/easycredit-module/tests'
  FULL_MODULE_PATH: '/tmp/oxid7/vendor/oxid-professional-services/easycredit-module'
  MODULE_BRANCH: 'dev-main'
  OXID_PATH: '/tmp/oxid7'

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # oxid-versions: ['dev-b-7.0-ce', 'dev-b-7.1-ce', 'dev-b-7.2-ce', 'dev-b-7.3-ce', 'dev-b-7.4-ce', 'dev-b-7.5-ce']
        oxid-versions: ['7.1']
        # php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        php-versions: ['8.2']
        exclude:
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.2'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.3'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.0-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.3'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.1-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.4'
          - oxid-versions: 'dev-b-7.2-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.3-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.4-ce'
            php-versions: '8.5'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.0'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.1'
          - oxid-versions: 'dev-b-7.5-ce'
            php-versions: '8.2'
    name: Oxid ${{ matrix.oxid-versions }} on PHP ${{ matrix.php-versions }}
    steps:
#      - name: Checkout
#        uses: actions/checkout@master

#      - name: Install PHP
#        uses: shivammathur/setup-php@master
#        with:
#          php-version: ${{ matrix.php-versions }}
#          extensions: mbstring, xdebug, gd, bcmath, ctype, curl, dom, hash, iconv, intl, openssl, simplexml, soap, xsl, zip
#          tools: composer:v2

#      - name: Check PHP Version
#        run: php -v

#      - name: Check Composer Version
#        run: composer -V
        
      - name: Cleanup workspace
        run: |
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./        
        
      - name: Clone testing environment
        run: git clone https://github.com/OXID-eSales/docker-eshop-sdk.git .

      - name: Clone the shop
        run: git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch b-${{ matrix.oxid-versions }}.x --single-branch source        

      - name: Prepare container configuration
        run: |
          make setup
          make addbasicservices
          make file=services/selenium-chrome.yml addservice
          perl -pi\
            -e "s#PHP_VERSION=.*#PHP_VERSION=${{ matrix.php-versions }}#g;"\
            .env
          perl -pi\
            -e "s#MYSQL_VERSION=.*#MYSQL_VERSION=5.7#g;"\
            .env
          perl -pi\
            -e 's#display_errors =.*#display_errors = false#g;'\
            -e 'print "xdebug.max_nesting_level=1000\nxdebug.mode=coverage\n\n"'\
            containers/php/custom.ini

          perl -pi\
            -e 's#/var/www/#/var/www/source/#g;'\
            containers/httpd/project.conf

      - name: Prepare shop configuration
        run: |
          cp source/source/config.inc.php.dist source/source/config.inc.php
          sed -i "1s+^+SetEnvIf Authorization "\(.*\)" HTTP_AUTHORIZATION=\$1\n\n+" source/source/.htaccess
          sed -i -e 's/<dbHost>/mysql/'\
                 -e 's/<dbUser>/root/'\
                 -e 's/<dbName>/example/'\
                 -e 's/<dbPwd>/root/'\
                 -e 's/<dbPort>/3306/'\
                 -e 's/<sShopURL>/https:\/\/localhost.local\//'\
                 -e 's/<sShopDir>/\/var\/www\/source\//'\
                 -e 's/<sCompileDir>/\/var\/www\/source\/tmp\//'\
              source/source/config.inc.php

      - name: Start containers
        run: |
          make up
          sleep 5

      - name: Checkout current module
        uses: actions/checkout@v5
        with:
          path: source/test-module

      - name: Install module
        run: |
          sed -i 's/"minimum-stability": "stable",/"minimum-stability": "dev",/' source/composer.json
          docker compose exec -T \
            php composer config repositories.${{ env.PACKAGE_NAME }} \
            --json '{"type":"path", "url":"./test-module", "options": {"symlink": true}}'
          docker compose exec -T \
            php composer config audit.block-insecure false
          docker compose exec -T \
            php composer require ${{ env.PACKAGE_NAME }}:* --no-interaction --no-update

      - name: Install Testing Library
        run: |
          docker compose exec -T php composer require oxid-esales/tests-deprecated-ce:dev-b-7.0.x --with-all-dependencies --no-update
          
      - name: Run tests
        run: |
          cp source/vendor/oxid-esales/testing-library/test_config.yml.dist source/test_config.yml
          docker compose exec -T \
            -e PARTIAL_MODULE_PATHS=${{ env.MODULE_PATH }} \
            -e ACTIVATE_ALL_MODULES=1 \
            -e RUN_TESTS_FOR_SHOP=0 \
            -e RUN_TESTS_FOR_MODULES=0 \
            -e XDEBUG_MODE=coverage \
            -e ADDITIONAL_TEST_PATHS='/var/www/vendor/${{ env.PACKAGE_NAME }}/tests' \
            php php vendor/bin/runtests \
              --coverage-clover=/var/www/coverage.xml \
              --coverage-text \
              --log-junit=/var/www/phpunit.xml \
              AllTestsUnit
          